### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by tedtieken** [JamesChevalier/Launch-Soon#4]
Repo appears to not have licensing info -- please add license file.

**Comment by JamesChevalier** [comment]
Thanks for bringing this up! I'm not sure how to handle this, though.

Right now, it's under the "Buy it, use it, break it, fix it, Trash it, change it, mail - upgrade it, Charge it, point it, zoom it, press it, Snap it, work it, quick - erase it, Write it, cut it, paste it, save it, Load it, check it, quick - rewrite it, Plug it, play it, burn it, rip it, Drag and drop it, zip - unzip it, Lock it, fill it, call it, find it, View it, code it, jam - unlock it, Surf it, scroll it, pause it, click it, Cross it, crack it, switch - update it, Name it, rate it, tune it, print it, Scan it, send it, fax - rename it, Touch it, bring it, pay it, watch it, Turn it, leave it, start - format it." license.
It's all free to use in whichever way people want, but I'm not sure which license is best for that.

In the future, I'll be adding images to the `app/assets/images` directory that won't be included in this license (they'll be free to use in this project, but users of this project aren't licensed to edit the images or use the images elsewhere). So, I'll need to figure out how to license the two pieces separately.

**Comment by tedtieken** [comment]
Put a text  file called LICENCE in the root directory.  

In it, share the license.  http://sam.zoy.org/wtfpl/ or http://opensource.org/licenses/MIT sound like they might be good fits for your motives

Add a second section to describe the image licenses, and a LICENSE file in that directory.

**Comment by JamesChevalier** [comment]
lol ... wtfpl might be the one!

Thanks for your help with this.

**Comment by JamesChevalier** [comment]
Added license file in JamesChevalier/Launch-Soon@5ae83aec3b52676577c19a9f3b3287722664ef93
