### ISSUE TITLE
Switch to official MailChimp gem

### ISSUE THREAD

**Issue by JamesChevalier** [JamesChevalier/Launch-Soon#5]
[Official Gem](https://rubygems.org/gems/mailchimp-api)
[Examples](https://github.com/mailchimp/mcapi2-ruby-examples)

**Comment by feriancek** [comment]
+1 
This would also be a move to the 2.0 API

**Comment by JamesChevalier** [comment]
Alright. I'm pretty sure I sorted this all out in [the last 5 commits on Sep 25, 2013](https://github.com/JamesChevalier/Launch-Soon/commits/master).

In the console, I notice that MailChimp fails on almost every other call ... I don't know what's up with that, or if that'll translate over to the website.

**Comment by feriancek** [comment]
On your MailChimp API page you can see the history of API calls, it may identify why some are failing? I'll be pulling this today while at work and will experiment with it on Heroku.

**Comment by JamesChevalier** [comment]
The MailChimp API history is only showing successes ... The error I get in the console is:

```
Excon::Errors::SocketError: EOFError (EOFError)
  from /Users/me/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:246:in `readline'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/excon-0.26.0/lib/excon/response.rb:39:in `parse'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/excon-0.26.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/excon-0.26.0/lib/excon/connection.rb:349:in `response'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/excon-0.26.0/lib/excon/connection.rb:252:in `request'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/excon-0.26.0/lib/excon/connection.rb:290:in `post'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/mailchimp-api-2.0.3/lib/mailchimp.rb:40:in `call'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/mailchimp-api-2.0.3/lib/mailchimp/api.rb:861:in `member_info'
  from (irb):5
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/railties-3.2.14/lib/rails/commands/console.rb:47:in `start'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/railties-3.2.14/lib/rails/commands/console.rb:8:in `start'
  from /Users/me/.rvm/gems/ruby-1.9.3-p448@launchsoon/gems/railties-3.2.14/lib/rails/commands.rb:41:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

I did a little searching on `Excon::Errors::SocketError: EOFError (EOFError)` and I came across [this carrierwave issue](https://github.com/carrierwaveuploader/carrierwave/issues/265), which seems to line up with my experiences and was reproducible ... If I let my console sit there for a little while, then make a call to MailChimp's API, it fails once with the error above but if I retry the same call it succeeds.

I don't think this issue will affect Launch-Soon, because there are no instances where a socket would be held open beyond the keep-alive value.

I saved this info [on stackoverflow](http://stackoverflow.com/questions/19030306/why-do-i-get-intermittent-exconerrorssocketerror-eoferror-eoferror-errors), to help others out.
